---

- hosts: all
  become: yes
  tasks:
    - include: tasks/01_common.yaml
    - include: tasks/02_apt.yaml
    - include: tasks/03_packages.yaml
    - include: tasks/04_accounts.yaml
    - include: tasks/05_tools.yaml
  tags: init

- hosts: all
  become: yes
  tasks:
    - include: tasks/06_nginx.yaml
      tags: nginx
    - include: tasks/07_mysql.yaml
      tags: mysql
    - include: tasks/08_supervisor.yaml
      tags: supervisor
    - include: tasks/09_memcached.yaml
      tags: memcached
    - include: tasks/10_mackerel.yaml
      tags: mackerel
